Neos:
  Flow:
    http:
      middlewares:
        minifyHtml:
          middleware: Carbon:Compression
          position: start
  Fusion:
    defaultContext:
      Carbon.Compression: Carbon\Compression\EelHelper\CompressionHelper
  Neos:
    fusion:
      autoInclude:
        "Carbon.Compression": true
