Neos:
  Flow:
    http:
      middlewares:
        minifyHtml:
          middleware: Carbon\Compression\Middleware\CompressionMiddleware
          position: 'before dispatch'
  Fusion:
    defaultContext:
      Carbon.Compression: Carbon\Compression\EelHelper\CompressionHelper
  Neos:
    fusion:
      autoInclude:
        Carbon.Compression: true
Carbon:
  Compression:
    debugMode: false
