Neos:
  Neos:
    fusion:
      autoInclude:
        'Carbon.Compression': true

Carbon:
  Compression:
    regex: '(?=[^<]*+(?:<(?!\/?(?:textarea|pre|script)\b)[^<]*+)*+(?:<(?>textarea|pre|script)\b|\z))'
    replace: ' '
